/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinanciero;

import static java.awt.Frame.MAXIMIZED_BOTH;
import proyectofinanciero.Inventario.Inventario;
import proyectofinanciero.Venta.FrmVenta;

/**
 *
 * @author pci
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public static DCompra dc;
    public static Proveedores p;
    public static Marca m;
    public static FrmVenta v;
    public Menu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        
        
         //MOSTRAR DASHBOARD
         btnDashboard.setBackground(new java.awt.Color(44,59,66));
         Dashboard.setVisible(true);
         
         btnInventario.setBackground(new java.awt.Color(44,59,66));
         Inventario.setVisible(false); 
         
         btnEmpleados.setBackground(new java.awt.Color(44,59,66));
         Empleados.setVisible(false);
         
         btnActivoFijo.setBackground(new java.awt.Color(44,59,66));
         ActivoFijo.setVisible(false);
         
         btnClientes.setBackground(new java.awt.Color(44,59,66));
         Clientes.setVisible(false);
         
         btnVentas.setBackground(new java.awt.Color(44,59,66));
         Ventas.setVisible(false);
         
         btnCxc.setBackground(new java.awt.Color(44,59,66));
         Cxc.setVisible(false);
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        Panel_menu2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        btnEmpleados = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JLabel();
        btnInventario = new javax.swing.JLabel();
        btnActivoFijo = new javax.swing.JLabel();
        btnCxc = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnVentas = new javax.swing.JLabel();
        btnClientes = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JLabel();
        Base = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Inventario = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Empleados = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ActivoFijo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Clientes = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Ventas = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Cxc = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_menu2.setBackground(new java.awt.Color(51, 51, 51));

        jTextField3.setBackground(new java.awt.Color(102, 102, 102));
        jTextField3.setBorder(null);

        btnEmpleados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setText("Empleados");
        btnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseClicked(evt);
            }
        });

        btnDashboard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });

        btnInventario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnInventario.setText("Inventario");
        btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventarioMouseClicked(evt);
            }
        });

        btnActivoFijo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActivoFijo.setForeground(new java.awt.Color(255, 255, 255));
        btnActivoFijo.setText("Activo Fijo");
        btnActivoFijo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActivoFijoMouseClicked(evt);
            }
        });

        btnCxc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCxc.setForeground(new java.awt.Color(255, 255, 255));
        btnCxc.setText("Cuentas por cobrar");
        btnCxc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCxcMouseClicked(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");

        btnVentas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setText("Ventas");
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }
        });

        btnClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes");
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });

        btnAyuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAyuda.setForeground(new java.awt.Color(255, 255, 255));
        btnAyuda.setText("Ayuda");

        javax.swing.GroupLayout Panel_menu2Layout = new javax.swing.GroupLayout(Panel_menu2);
        Panel_menu2.setLayout(Panel_menu2Layout);
        Panel_menu2Layout.setHorizontalGroup(
            Panel_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_menu2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addGroup(Panel_menu2Layout.createSequentialGroup()
                        .addGroup(Panel_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActivoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCxc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_menu2Layout.setVerticalGroup(
            Panel_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_menu2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActivoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnCxc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        Base.setBackground(new java.awt.Color(255, 255, 255));
        Base.setLayout(new java.awt.CardLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Dashboard");

        jLabel16.setText("Trafico del CPU");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel9))
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel16)))
                .addContainerGap(926, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel9)
                .addGap(71, 71, 71)
                .addComponent(jLabel16)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        Base.add(Dashboard, "card2");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Inventario");

        javax.swing.GroupLayout InventarioLayout = new javax.swing.GroupLayout(Inventario);
        Inventario.setLayout(InventarioLayout);
        InventarioLayout.setHorizontalGroup(
            InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel10)
                .addContainerGap(935, Short.MAX_VALUE))
        );
        InventarioLayout.setVerticalGroup(
            InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel10)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        Base.add(Inventario, "card3");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Empleado");

        javax.swing.GroupLayout EmpleadosLayout = new javax.swing.GroupLayout(Empleados);
        Empleados.setLayout(EmpleadosLayout);
        EmpleadosLayout.setHorizontalGroup(
            EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpleadosLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel11)
                .addContainerGap(941, Short.MAX_VALUE))
        );
        EmpleadosLayout.setVerticalGroup(
            EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpleadosLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel11)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        Base.add(Empleados, "card4");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("Activo Fijo");

        javax.swing.GroupLayout ActivoFijoLayout = new javax.swing.GroupLayout(ActivoFijo);
        ActivoFijo.setLayout(ActivoFijoLayout);
        ActivoFijoLayout.setHorizontalGroup(
            ActivoFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActivoFijoLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel12)
                .addContainerGap(932, Short.MAX_VALUE))
        );
        ActivoFijoLayout.setVerticalGroup(
            ActivoFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActivoFijoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel12)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        Base.add(ActivoFijo, "card5");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("Clientes");

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel13)
                .addContainerGap(973, Short.MAX_VALUE))
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel13)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        Base.add(Clientes, "card6");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setText("Ventas");

        javax.swing.GroupLayout VentasLayout = new javax.swing.GroupLayout(Ventas);
        Ventas.setLayout(VentasLayout);
        VentasLayout.setHorizontalGroup(
            VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentasLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel14)
                .addContainerGap(990, Short.MAX_VALUE))
        );
        VentasLayout.setVerticalGroup(
            VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentasLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel14)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        Base.add(Ventas, "card7");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setText("Cuentas por cobrar");

        javax.swing.GroupLayout CxcLayout = new javax.swing.GroupLayout(Cxc);
        Cxc.setLayout(CxcLayout);
        CxcLayout.setHorizontalGroup(
            CxcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CxcLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel15)
                .addContainerGap(792, Short.MAX_VALUE))
        );
        CxcLayout.setVerticalGroup(
            CxcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CxcLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel15)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        Base.add(Cxc, "card8");

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addComponent(Panel_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalLayout.createSequentialGroup()
                    .addContainerGap(237, Short.MAX_VALUE)
                    .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_menu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 153, 255));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sesion (1).png"))); // NOI18N
        jMenu2.setText("Log in");

        jMenu10.setText("Iniciar Sesión");
        jMenu2.add(jMenu10);

        jMenu11.setText("Nuevo Usuario");
        jMenu2.add(jMenu11);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inv(1).png"))); // NOI18N
        jMenu5.setText("Inventario");

        jMenu20.setText("Proveedores");
        jMenu20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu20MouseClicked(evt);
            }
        });
        jMenu5.add(jMenu20);

        jMenu18.setText("Categorias");
        jMenu18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu18MouseClicked(evt);
            }
        });
        jMenu5.add(jMenu18);

        jMenu19.setText("Marcas");
        jMenu19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu19MouseClicked(evt);
            }
        });
        jMenu5.add(jMenu19);

        jMenu7.setText("Compras");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu5.add(jMenu7);

        jMenu21.setText("Productos");
        jMenu21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu21MouseClicked(evt);
            }
        });
        jMenu5.add(jMenu21);

        jMenu6.setText("Control de Inventario");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu5.add(jMenu6);

        jMenuBar1.add(jMenu5);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados (1)_1.png"))); // NOI18N
        jMenu3.setText("Empleados");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/af2.png"))); // NOI18N
        jMenu4.setText("Activo Fijo");

        jMenu8.setText("Catálogo de Códigos");
        jMenu4.add(jMenu8);

        jMenu16.setText("Bienes");
        jMenu4.add(jMenu16);

        jMenu12.setText("Depreciación");
        jMenu4.add(jMenu12);

        jMenuBar1.add(jMenu4);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente_(1)_1.png"))); // NOI18N
        jMenu13.setText("Clientes");
        jMenuBar1.add(jMenu13);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas.jpg"))); // NOI18N
        jMenu9.setText("Ventas");

        jMenu1.setText("Nueva Venta");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu9.add(jMenu1);

        jMenuBar1.add(jMenu9);

        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5b862755be2ecabf81698a5f1795572c(1).png"))); // NOI18N
        jMenu15.setText("Cuentas por cobrar");

        jMenu17.setText("Abonos a cuenta");
        jMenu15.add(jMenu17);

        jMenuBar1.add(jMenu15);

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ayuda2_1.png"))); // NOI18N
        jMenu14.setText("Ayuda");
        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
        dc = new DCompra();
        dc.setVisible(true);
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu20MouseClicked
        // TODO add your handling code here:
        p = new Proveedores();
        p.setVisible(true);
    }//GEN-LAST:event_jMenu20MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        Empleados emp = new Empleados();
        emp.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu19MouseClicked
        // TODO add your handling code here:
        m = new Marca();
        m.setVisible(true);
    }//GEN-LAST:event_jMenu19MouseClicked

    private void jMenu18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu18MouseClicked
        // TODO add your handling code here:
        Category cat = new Category();
        cat.setVisible(true);
    }//GEN-LAST:event_jMenu18MouseClicked

    private void jMenu21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu21MouseClicked
        // TODO add your handling code here:
        Productos p = new Productos();
        p.setVisible(true);
    }//GEN-LAST:event_jMenu21MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        Inventario i = new Inventario();
        i.setVisible(true);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        v = new FrmVenta();
        v.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked

        //MOSTRAR DASHBOARD
         btnDashboard.setBackground(new java.awt.Color(44,59,66));
         Dashboard.setVisible(true);
         
         btnInventario.setBackground(new java.awt.Color(44,59,66));
         Inventario.setVisible(false); 
         
         btnEmpleados.setBackground(new java.awt.Color(44,59,66));
         Empleados.setVisible(false);
         
         btnActivoFijo.setBackground(new java.awt.Color(44,59,66));
         ActivoFijo.setVisible(false);
         
         btnClientes.setBackground(new java.awt.Color(44,59,66));
         Clientes.setVisible(false);
         
         btnVentas.setBackground(new java.awt.Color(44,59,66));
         Ventas.setVisible(false);
         
         btnCxc.setBackground(new java.awt.Color(44,59,66));
         Cxc.setVisible(false);
         
         
        
        
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked

         //MOSTRAR CLIENTES
         btnDashboard.setBackground(new java.awt.Color(44,59,66));
         Dashboard.setVisible(false);
         
         btnInventario.setBackground(new java.awt.Color(44,59,66));
         Inventario.setVisible(false); 
         
         btnEmpleados.setBackground(new java.awt.Color(44,59,66));
         Empleados.setVisible(false);
         
         btnActivoFijo.setBackground(new java.awt.Color(44,59,66));
         ActivoFijo.setVisible(false);
         
         btnClientes.setBackground(new java.awt.Color(44,59,66));
         Clientes.setVisible(true);
         
         btnVentas.setBackground(new java.awt.Color(44,59,66));
         Ventas.setVisible(false);
         
         btnCxc.setBackground(new java.awt.Color(44,59,66));
         Cxc.setVisible(false);
         
         
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseClicked

         //MOSTRAR INVENTARIOS
         btnDashboard.setBackground(new java.awt.Color(44,59,66));
         Dashboard.setVisible(false);
         
         btnInventario.setBackground(new java.awt.Color(44,59,66));
         Inventario.setVisible(true); 
         
         btnEmpleados.setBackground(new java.awt.Color(44,59,66));
         Empleados.setVisible(false);
         
         btnActivoFijo.setBackground(new java.awt.Color(44,59,66));
         ActivoFijo.setVisible(false);
         
         btnClientes.setBackground(new java.awt.Color(44,59,66));
         Clientes.setVisible(false);
         
         btnVentas.setBackground(new java.awt.Color(44,59,66));
         Ventas.setVisible(false);
         
         btnCxc.setBackground(new java.awt.Color(44,59,66));
         Cxc.setVisible(false);
         

         
    }//GEN-LAST:event_btnInventarioMouseClicked

    private void btnEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseClicked

         //MOSTRAR EMPLEADOS
         btnDashboard.setBackground(new java.awt.Color(44,59,66));
         Dashboard.setVisible(false);
         
         btnInventario.setBackground(new java.awt.Color(44,59,66));
         Inventario.setVisible(false); 
         
         btnEmpleados.setBackground(new java.awt.Color(44,59,66));
         Empleados.setVisible(true);
         
         btnActivoFijo.setBackground(new java.awt.Color(44,59,66));
         ActivoFijo.setVisible(false);
         
         btnClientes.setBackground(new java.awt.Color(44,59,66));
         Clientes.setVisible(false);
         
         btnVentas.setBackground(new java.awt.Color(44,59,66));
         Ventas.setVisible(false);
         
         btnCxc.setBackground(new java.awt.Color(44,59,66));
         Cxc.setVisible(false);
         
        
    }//GEN-LAST:event_btnEmpleadosMouseClicked

    private void btnActivoFijoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivoFijoMouseClicked

         //MOSTRAR ACTIVO FIJO
         btnDashboard.setBackground(new java.awt.Color(44,59,66));
         Dashboard.setVisible(false);
         
         btnInventario.setBackground(new java.awt.Color(44,59,66));
         Inventario.setVisible(false); 
         
         btnEmpleados.setBackground(new java.awt.Color(44,59,66));
         Empleados.setVisible(false);
         
         btnActivoFijo.setBackground(new java.awt.Color(44,59,66));
         ActivoFijo.setVisible(true);
         
         btnClientes.setBackground(new java.awt.Color(44,59,66));
         Clientes.setVisible(false);
         
         btnVentas.setBackground(new java.awt.Color(44,59,66));
         Ventas.setVisible(false);
         
         btnCxc.setBackground(new java.awt.Color(44,59,66));
         Cxc.setVisible(false);
         
         
    }//GEN-LAST:event_btnActivoFijoMouseClicked

    private void btnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseClicked

         //MOSTRAR VENTAS
         btnDashboard.setBackground(new java.awt.Color(44,59,66));
         Dashboard.setVisible(false);
         
         btnInventario.setBackground(new java.awt.Color(44,59,66));
         Inventario.setVisible(false); 
         
         btnEmpleados.setBackground(new java.awt.Color(44,59,66));
         Empleados.setVisible(false);
         
         btnActivoFijo.setBackground(new java.awt.Color(44,59,66));
         ActivoFijo.setVisible(false);
         
         btnClientes.setBackground(new java.awt.Color(44,59,66));
         Clientes.setVisible(false);
         
         btnVentas.setBackground(new java.awt.Color(44,59,66));
         Ventas.setVisible(true);
         
         btnCxc.setBackground(new java.awt.Color(44,59,66));
         Cxc.setVisible(false);
         
         
    }//GEN-LAST:event_btnVentasMouseClicked

    private void btnCxcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCxcMouseClicked

         //MOSTRAR CUENTAS POR COBRAR
         btnDashboard.setBackground(new java.awt.Color(44,59,66));
         Dashboard.setVisible(false);
         
         btnInventario.setBackground(new java.awt.Color(44,59,66));
         Inventario.setVisible(false); 
         
         btnEmpleados.setBackground(new java.awt.Color(44,59,66));
         Empleados.setVisible(false);
         
         btnActivoFijo.setBackground(new java.awt.Color(44,59,66));
         ActivoFijo.setVisible(false);
         
         btnClientes.setBackground(new java.awt.Color(44,59,66));
         Clientes.setVisible(false);
         
         btnVentas.setBackground(new java.awt.Color(44,59,66));
         Ventas.setVisible(false);
         
         btnCxc.setBackground(new java.awt.Color(44,59,66));
         Cxc.setVisible(true);
         

         
    }//GEN-LAST:event_btnCxcMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActivoFijo;
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Cxc;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Empleados;
    private javax.swing.JPanel Inventario;
    private javax.swing.JPanel Panel_menu;
    private javax.swing.JPanel Panel_menu1;
    private javax.swing.JPanel Panel_menu2;
    private javax.swing.JPanel Principal;
    private javax.swing.JPanel Ventas;
    private javax.swing.JLabel btnActivoFijo;
    private javax.swing.JLabel btnAyuda;
    private javax.swing.JLabel btnClientes;
    private javax.swing.JLabel btnCxc;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnEmpleados;
    private javax.swing.JLabel btnInventario;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
